name: Test
on: [push, pull_request]

jobs:
  phpunit:
    name: PHP-${{ matrix.php_version }}-${{ matrix.perfer }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version:
          - 5.6
          - 7.0
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
        perfer:
          - stable
          - lowest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer install && composer update --prefer-dist --no-interaction --no-suggest --prefer-${{ matrix.perfer }}
    - name: Generate key
      run: openssl genrsa -out app_private_key.pem && openssl rsa -in app_private_key.pem -pubout -out app_public_key.pem
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit tests/MerchantTest.php
